### ISSUE TITLE
Terraform folder missing in chapter-10

### ISSUE THREAD

**Issue by karuneesh** [PacktPublishing/Delivering-Microservices-with-AWS#1]
Chapter 10 mentions use of Terraform. The code repository in GitHub misses the Terraform folder in Chapter-10 where as it is present in chapter-11. Please see through the missing folder for chapter 10 in github repo of [Building-and-Delivering-Microservices-on-AWS](https://github.com/PacktPublishing/Building-and-Delivering-Microservices-on-AWS). Best Regards Karuneesh Bagga

**Comment by teach-me-more** [comment]
Code have been pushed and issue is resolved. Please check again.
